### ISSUE TITLE
Frame Stuttering at CoX issues

### ISSUE THREAD

**Issue by bugrs** [open-osrs/runelite#2279] opened 2020-01-23 07:14 UTC
**Describe the bug**
After 2 to 3 hours of the client being loaded, when entering Chambers of Xeric the client begins stuttering violently and becomes unplayable. Leaving the raid you were in or restarting the client fixes this issue entirely. What's interesting is that the issue, when it occurs, persists across clients even if you open it after the issue begins, See gif in screenshots.

**To Reproduce**
Have the client open for 2 to 3 hours, ideally in Chambers of Xeric

**Expected behavior**
A lack of lag/frame/stuttering issues

**Screenshots**
https://i.imgur.com/A9t8Mjq.gifv

Game login screen stuttering after being opened when the issue began happening. Issue resolves itself on both clients if you leave the raid you are in.

**Environment (please complete the following information):**
Windows 10, OpenRs, latest launcher
Java is up to date
Disabling GPU and all externals and all cox related plugins does not resolve the issue
Disabling Hardware acceleration does not resolve the issue

**Additional context**
This is an incredibly frustrating problem when soloing chambers of xeric as you are forced to leave the raid.

**Comment by SRLJustin** [comment] 2020-01-23 08:20
+1 on this issue with stable .exe - Moved to building the client and using the .jar and don't have this issue

**Comment by dutta64** [comment] 2020-01-29 18:33
Also experienced this issue. I thought it might be the AOE plugin for Olm, but disabling it did not fix the issue. The stuttering occurred around ~3 hours, and eventually my client froze completely.

Win 10/GTX 1070/Nightly

**Comment by bugrs** [comment] 2020-01-30 08:29
Tried building the Jar as SRLJustin did and still experience this issue.

**Comment by uupiits** [comment] 2020-02-11 22:11
this issue been around for atleast a year

**Comment by Ganom** [comment] 2020-02-11 22:19
Considering the project hasn't been around for a year, i'd say thats a big exaggerated, but as said before, we cannot reproduce the issue on our machines, which means we can't profile it. Any insight into what can cause it, is reproducible, and doesn't require hours on end of gameplay would be super helpful.

**Comment by Jawnb64** [comment] 2020-02-11 23:15
Its very consistent to reproduce, but it does take a few hours of CoX in order for it to resurface.  I've included my daily log of the last time it happened, I can't remember the exact time it occurred unfortunately. When it happens again I'll grab the log immediately. 
[client_2020-02-10.0.log](https://github.com/open-osrs/runelite/files/4189088/client_2020-02-10.0.log)

**Comment by ThatGamerBlue** [comment] 2020-02-11 23:41
@Jawnb64 few questions: what's your slayer task, and how reliable is your internet connection

**Comment by Jawnb64** [comment] 2020-02-11 23:53
Hell hounds, but I've had multiple different slayer tasks since this issue popped up 2 weeks ago. 

My internet is very reliable, except during scheduled maintenance hours (1am-5am EST) where it will be choppy for around 5 minutes. This only happens once per night if at all.

**Comment by xKylee** [comment] 2020-02-12 00:04
Anyone wanna let me leech cox for 3 hours and see if I can Reproduce this issue?

**Comment by cellium** [comment] 2020-02-19 01:42
this issue also happens to me everytime I do solo cox. works for a raid or two, then randomly within a raid frames drop and it becomes completely unplayable.

**Comment by edgar1016** [comment] 2020-02-21 10:24
Has been happening to me as well but only at CoX when it crashes here's what my log came up with. 
@danwong also has the same error in issue #2338 
`2020-02-21 03:12:11 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.desktop/java.awt.image.BufferedImage.<init>(Unknown Source)
	at net.runelite.client.plugins.gpu.GpuPlugin.screenshot(GpuPlugin.java:1260)
	at net.runelite.client.plugins.gpu.GpuPlugin$$Lambda$993/0x0000000100b2c440.get(Unknown Source)
	at net.runelite.client.ui.DrawManager.processDrawComplete(DrawManager.java:84)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1160)
	at bf.onPost(GameShell.java:86)
	at bf.g(GameShell.java)
	at bf.run(GameShell.java:328)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by xKylee** [comment] 2020-02-21 10:38
The above error means that your computer run out of memory.

It’s also not a particularly helpful error because it doesn’t tell us anything other than your machine ran out of memory.

What specs are your machines?

**Comment by edgar1016** [comment] 2020-02-21 10:48
MOBO: MSI Z370 Pro
CPU: IntelCore i7-8700 CPU @ 3.20GHz
GPU: AMD Radeon RX 580 4gb
RAM: 16gb DDR4

**Comment by cellium** [comment] 2020-02-21 11:12
I've been avoiding the stuttering the last few days by restarting the client every few raids. It only occurs if the client is opened for a few hours. If there's anyway I can assist in diagnosing the cause pls let me know though, I'd like to help if possible.

**Comment by ThatGamerBlue** [comment] 2020-03-25 22:37
is this fixed?

**Comment by redeems** [comment] 2020-04-02 00:51
@cellium if you experience this issue again, an updated log at the time of reproduction would be really helpful.

**Comment by Lorenso0** [comment] 2020-04-08 23:03
This issue still happens. The client was working fine all day (had it open for 10+ hours) and then suddenly mid-raid lag spikes started happening. When this happens it keeps spiking from 50 to 42 FPS. 
I've checked my logs but there's nothing in there, if it happens again I could have someone teamviewer over to my PC or something to see if anything useful can be found?

**Comment by Lorenso0** [comment] 2020-04-09 10:42
It just happened again, checked my logs and saw this:
2020-04-09 11:40:15 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at net.runelite.client.ui.overlay.OverlayUtil.renderTextLocation(OverlayUtil.java:154)
	at net.runelite.client.plugins.lootassist.LootAssistOverlay.render(LootAssistOverlay.java:90)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:500)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:232)
	at net.runelite.client.callback.Hooks.drawScene(Hooks.java:426)
	at ej.ad(Scene.java:315)
	at hj.gn(Coord.java:4337)
	at iv.io(StudioGame.java:9896)
	at hy.ik(MusicPatch.java:9785)
	at client.gc(Client.java:4086)
	at client.ao(Client.java:1182)
	at br.ar(GameShell.java:362)
	at br.run(GameShell.java:316)
	at java.base/java.lang.Thread.run(Unknown Source)

Maybe it's related to this issue? The lag started happening not too long after that error

**Comment by Lorenso0** [comment] 2020-04-09 22:48
Happened again. This time, instead of closing the client I decided to try re-logging. This seems to fix the issue. 

So if anyone reads this while it's not fixed yet, just log out and back in every 2 hours or so.

**Comment by CJP10** [comment] 2020-06-19 16:44
@Lorenso0 try disabling Loot Assist

**Closed** 2020-06-26 20:48 UTC
Labels: needs-info
