### ISSUE TITLE
Launcher should remember nightly vs stable

### ISSUE THREAD

**Issue by chrisjohnson** [open-osrs/runelite#1887] opened 2019-11-05 13:55 UTC
**Is your feature request related to a problem? Please describe.**
Having to remember to pick stable vs nightly on each launch is annoying.

**Describe the solution you'd like**
Add a checkbox for "remember me". This would also require a button or setting to be able to switch back later

**Comment by Owain94** [comment] 2019-11-05 15:15
The problem is that when artifacts are already downloaded it’s possible that the launcher only showS for a split second which makes clicking a button to change branch pretty hard.

**Comment by chrisjohnson** [comment] 2019-11-05 16:01
Is it possible that the client could modify settings that the launcher uses? Or are they totally separate? You could manage the option from within openosrs itself after setting it initially if they are allowed to interact, and that's frankly the much more intuitive behavior since to the end user, the launcher and the client are one package.

Or another possibility is to ensure that the loader stays visible for at least 10 seconds, giving them time to adjust the settings. Or you could use the BIOS approach, if you hold or press a certain button while it's starting, it'll stop loading the app and leave you on the launcher window until you select.

Worst case, some wiki instructions on how to manually clear the setting would do.

**Comment by zeruth** [comment] 2019-11-05 18:48
Imho this is a wontfix. Nothing really wrong with clicking a button to start the client from the launcher. And then resetting your preference would be a hassle. Not worth the effort.

**Comment by chrisjohnson** [comment] 2019-11-05 18:54
I mean, it's certainly possible to implement UX that doesn't make it a hassle, I just offered a few ideas. I understand that you personally don't want to take the time to implement it because you don't find it to be worth the effort, but does that mean nobody should? Would you actively reject a PR that added such a UX improvement?

**Comment by zeruth** [comment] 2019-11-05 18:59
Most likely resetting would have to be done in client, since the launcher loads so fast. AMD certainly we would accept a PR but we wouldnt enforce that launcher update.

**Comment by chrisjohnson** [comment] 2019-11-05 19:01
I think "hold esc to pause launcher" would be a pretty unobtrusive
compromise. I'll see if I can come up with something.

**Comment by pklite** [comment] 2019-11-06 21:10
^ sounds like a great idea

**Closed** 2020-02-06 00:06 UTC
Labels: enhancement, no-issue-activity
